### ISSUE TITLE
[Pre-release][on Build] src/Core/BlockChain.cpp - error: ‘header_cache’ was not declared in this scope

### ISSUE THREAD

**Issue by RanDomPiouPiou** [dirtybits/catalyst#10]
Related to this commit:
https://github.com/dirtybits/catalyst/commit/c3b8c62d345c14eb6de88e502efc91c73174a23c#diff-9154d2d721da3f53f81967b96e18be8d

Rows 105/106.
After this change, header_cache is no longer declared for BlockChain.cpp.

**Comment by dirtybits** [comment]
As I'm basing this project off what bytecoin, I imagine it's related to this:
https://github.com/bcndev/bytecoin/commit/e0e63e7e0102ca6bea56913d6a70e3c5b256ead7
I'll be going though updating files to match theirs.

**Comment by dirtybits** [comment]
As I'm basing this project off bytecoin, I imagine it's related to this:
bcndev/bytecoin@e0e63e7
I'll be going though updating files to match theirs.

**Comment by RanDomPiouPiou** [comment]
Are you looking into fixing this specifically, or basing it as much as possible to the current status of their project ?

**Comment by RanDomPiouPiou** [comment]
Potential fix with migration thanks to pull request #12

**Comment by dirtybits** [comment]
Looks like that worked.
