### ISSUE TITLE
[Sticky] Are early feedbacks expected ?

### ISSUE THREAD

**Issue by RanDomPiouPiou** [dirtybits/catalyst#3]
Hi @dirtybits 

Are early feedback expected regarding commits that are performed ?
Should we wait for a first release, or any feedback would be appreciated ?

Thanks,
RanDom

**Comment by dirtybits** [comment]
Hey @RanDomPiouPiou, 

While I do expect the first release to be ready soon (hopefully in the next week or so),
any feedback in the meantime is welcome.

Thank you,
~dirtybits
