### ISSUE TITLE
[Pre-release][on Build]  error: no matching function for call to ‘catalyst::BlockChainState::get_tip_segment

### ISSUE THREAD

**Issue by RanDomPiouPiou** [dirtybits/catalyst#7]
When trying to build with master branch on May 25th (After merging pull request):

 error: no matching function for call to ‘catalyst::BlockChainState::get_tip_segment(const catalyst::api::BlockHeader&, catalyst::Height&, bool) const’
   auto timestamps_window = get_tip_segment(prev_info, blocks_count, false);

=> Related to src/Core/BlockChain.hpp
See commit @row47: https://github.com/dirtybits/catalyst/commit/c3b8c62d345c14eb6de88e502efc91c73174a23c

When rollbacked, compilation succeeds.
Code missing to implement the current function ?

**Comment by dirtybits** [comment]
Looking into this, thank you.

**Comment by RanDomPiouPiou** [comment]
Potential fix with migration to 3.11 with pull request #12
