### ISSUE TITLE
[Pre-release][on Build]  error: ‘CATALYST_NETWORK’ was not declared in this scope

### ISSUE THREAD

**Issue by RanDomPiouPiou** [dirtybits/catalyst#8]
On May 25th, when building with current source, including the get_tip_segment rollback, the following error is faced:

 error: ‘CATALYST_NETWORK’ was not declared in this scope
     , network_id(CATALYST_NETWORK)

=> Directly related to config.cpp @row23 - Needs to be either uncommented, or fixed.

**Comment by dirtybits** [comment]
I'm still doing some network configuration, but thank you for noting this.
